version: '3.5'


volumes:
  es2data:
  esdata:
  lsdata:
  kibanadata:


services:
  elasticsearch2:
    image: elasticsearch:2
    restart: unless-stopped
    environment:
      ES_HEAP_SIZE: "${ES_MEMORY_LIMIT}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9202:9202
      - 9302:9302
    volumes:
      - type: volume
        source: es2data
        target: /usr/share/elasticsearch/data
    command: >
      -Des.index.number_of_shards=1
      -Des.index.number_of_replicas=0
      -Des.node.local=true
      -Des.bootstrap.memory_lock=true
      -Des.xpack.monitoring.enabled=false
      -Des.http.port=9202

  elasticsearch:
    build:
      context: "${FACTOTUM_ELASTIC_DIR}"
      dockerfile: "${FACTOTUM_DIR}/docker/dockerfiles/Dockerfile.elasticsearch"
    image: factotum-elasticsearch
    restart: unless-stopped
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      xpack.monitoring.enabled: "false"
      ES_JAVA_OPTS: "-Xms${ES_MEMORY_LIMIT} -Xmx${ES_MEMORY_LIMIT}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data

  kibana:
    image: kibana:6.7.2
    restart: unless-stopped
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      XPACK_MONITORING_ENABLED: "false"
    ports:
      - 5601:5601
    volumes:
      - type: volume
        source: kibanadata
        target: /usr/share/kibana/data
    depends_on:
      - elasticsearch

  logstash:
    build:
      context: "${FACTOTUM_ELASTIC_DIR}"
      dockerfile: "${FACTOTUM_DIR}/docker/dockerfiles/Dockerfile.logstash"
    image: factotum-logstash
    restart: "no"
    environment:
      ELASTICSEARCH_HOST: elasticsearch:9200
      SQL_DATABASE: "${SQL_DATABASE}"
      SQL_USER: "${SQL_USER}"
      SQL_PASSWORD: "${SQL_PASSWORD}"
      SQL_HOST: host.docker.internal
      SQL_PORT: 3306
      JDBC_DRIVER_LIBRARY: "/opt/mysql-connector.jar"
      XPACK_MONITORING_ENABLED: "false"
      LS_JAVA_OPTS: "-Xms${LS_MEMORY_LIMIT} -Xmx${LS_MEMORY_LIMIT}"
    volumes:
      - type: volume
        source: lsdata
        target: /usr/share/logstash/data
    depends_on:
      - elasticsearch
